export interface StreamerDetails {
  'api-jar': string
  asap: string
  audience_count: string
  bot_count: string
  channel_id: string
  channel_key: string
  comment_count: string
  cover_image: string
  created_at: string
  description: string
  diamond_ratio: string
  diamond_receiver: string
  diamonds: string
  duration: string
  featured: string
  game_id: string
  game_img: string
  game_name: string
  gifts: string
  guesthost: string
  highlight_count: string
  id: string
  is_game: string
  is_pbb: string
  is_win: string
  landscape: string
  latitude: string
  like_count: string
  live_end_time: string
  live_highest_audience: string
  live_start_time: string
  live_type: string
  liveuser: {
    avatar: string
    avatar_small: string
    badge: []
    channel_id: string
    cohost_livestream_notification: number
    create_date: string
    create_time: number
    follower_number: number
    following_number: number
    game: number
    gender: number
    guid: string
    hide_timeline_from: number
    hide_timeline_to: number
    id: number
    intro: string
    isLive: number
    is_favorite: number
    is_kumuversary: number
    is_mute: false
    is_suggest: string
    level: number
    live_dur: string
    ministore: number
    nickname: string
    relation_status: number
    tier: string
    timeline_privacy: number
    title: string
    type: number
    uid: number
    user_live_notification: number
    user_status: string
    username: string
    vip_level: string
    vip_pop_up: string
    visitor: string
    website: string
  }
  location: string
  longitude: string
  n_xdg: string
  notification_sound: string
  post_status: string
  post_timeline: string
  relation_status: number
  replay_highest_audience: string
  rtm_token: string
  rtm_user_id: string
  rtmp: string
  sale_count: string
  schedule: string
  scheduled_time: string
  share_count: string
  short_id: string
  show_chat: string
  signal_token: string
  slots: []
  sponsor: string
  test: string
  title: string
  total_bonus: string
  total_joined_times: string
  total_viewer: string
  trivia_type: string
  type: string
  user_id: string
  video: string
  video_url: string
}
