export interface StreamerInfo {
  user_short_id: number
  nickname: string
  username: string
  is_suggest: string
  avatar: string
  user_type: string
  asap: string
  country: string
  country_code: string
  respective_number: string
  tier: string
  id: number
  game_id: number
  is_game: string
  game_name: string
  game_img: string
  feed_id: string
  is_pbb: string
  channel_id: string
  user_id: string
  user_info: {
    relation_status: number
    follower_number: number
  }
  title: string
  cover_image: string
  cover_image_screenshots: string
  type: number
  live_type: number
  scheduled_time: number
  replay_count: number
  category: string[]
  hashtag: string
  is_spg: number
  language: string[]
  landscape: number
  is_win: number
  video: number
  pk_status: number
  featured: number
  audience_count: number
  is_shoplight: number
  spotlight_host_title: string
  is_recommend: number
  short_id: number
  uid: string
}
